import React, { useState } from 'react';
import { useAnalysis } from '../../context/AnalysisContext';
import { Card, CardHeader, CardTitle, CardContent } from '../ui/Card';
import Button from '../ui/Button';
import { ShieldAlert, Copy, Share2, Download, CheckCircle2, Shield, Eye, X, Users, Activity } from 'lucide-react';

const ProtectOthersSection = () => {
  const { analysisResult: result } = useAnalysis();
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [showConfirmationModal, setShowConfirmationModal] = useState(false);
  const [alertContent, setAlertContent] = useState('');
  const [isSharing, setIsSharing] = useState(false);

  if (!result) return null;

  // Generate alert content based on analysis result and community intelligence
  const generateAlertContent = () => {
    const threatId = result.community_intelligence?.threat_id || `SMR-${Date.now().toString(36).toUpperCase()}`;
    const threatFamily = result.community_intelligence?.threat_family || result.category || 'Unknown';
    const threatLevel = getThreatLevel(result.verdict, result.confidence);
    const reportCount = result.community_intelligence?.report_count || 0;
    const timestamp = new Date().toLocaleString();
    const explanation = result.explanation || 'No explanation available.';
    const safetyRecommendations = Array.isArray(result.recommended_actions) && result.recommended_actions.length > 0
      ? result.recommended_actions.join('\n')
      : 'No specific safety recommendations available.';

    return `
🚨 COMMUNITY ALERT: ${threatFamily} Scam Detected 🚨

Threat ID: ${threatId}
Threat Family: ${threatFamily}
Threat Level: ${threatLevel}
Community Reports: ${reportCount} reports in our network
Detection Time: ${timestamp}

📝 AI Analysis:
${explanation}

🛡️ Safety Recommendations:
${safetyRecommendations}

This alert was generated by ScamMirror AI to help protect our community threat intelligence network.
Stay vigilant and report suspicious activity.

#ScamAlert #CommunityShield
    `.trim();
  };

  const getThreatLevel = (verdict, confidence) => {
    const lower = verdict.toLowerCase();
    if (lower.includes('scam') || confidence >= 0.7) return 'HIGH';
    if (lower.includes('safe') || confidence <= 0.3) return 'LOW';
    return 'MEDIUM';
  };

  const handleGenerateAlert = () => {
    setAlertContent(generateAlertContent());
    setShowGenerateModal(false);
    setShowPreviewModal(true);
  };

  const handleCopyAlert = async () => {
    try {
      await navigator.clipboard.writeText(alertContent);
      alert('Alert copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy: ', err);
      alert('Failed to copy alert to clipboard');
    }
  };

  const handleShareAlert = async () => {
    setIsSharing(true);
    try {
      if (navigator.share) {
        await navigator.share({
          title: `Scam Alert: ${result.community_intelligence?.threat_family || result.category || 'Unknown'} Scam Detected`,
          text: alertContent,
        });
        // Success - show confirmation
        setIsSharing(false);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
      } else {
        // Fallback to copy
        await navigator.clipboard.writeText(alertContent);
        setIsSharing(false);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
        alert('Alert copied to clipboard. Share it manually to protect others.');
      }
    } catch (err) {
      console.error('Share failed: ', err);
      setIsSharing(false);
      // Fallback to copy on error
      try {
        await navigator.clipboard.writeText(alertContent);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
        alert('Alert copied to clipboard. Share it manually to protect others.');
      } catch (copyErr) {
        alert('Failed to share or copy alert');
      }
    }
  };

  const handleDownloadAlert = () => {
    // Download as .txt file
    const blob = new Blob([alertContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scam-alert-${result.community_intelligence?.threat_id || 'unknown'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCloseModal = () => {
    setShowGenerateModal(false);
    setShowPreviewModal(false);
    setShowConfirmationModal(false);
    setIsSharing(false);
  };

  return (
    <>
      <Card className="h-full bg-surface/50 backdrop-blur-xl border-border">
        <CardHeader className="pb-2">
          <CardTitle className="text-xl font-display flex items-center text-white">
            <ShieldAlert className="w-5 h-5 text-primary mr-3" />
            Protection & Actions
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-gray-400 mb-6 text-sm">
            Help protect our community by sharing verified scam alerts. Generate a community alert to warn others about this threat.
          </p>

          <div className="space-y-4">
            <Button 
              onClick={() => setShowGenerateModal(true)} 
              className="w-full h-12 bg-danger hover:bg-danger-hover text-white flex items-center justify-center border-0"
            >
              <ShieldAlert className="w-5 h-5 mr-2" />
              Generate Community Alert
            </Button>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              <Button variant="secondary" onClick={handleCopyAlert} disabled={isSharing} className="w-full">
                <Copy className="w-4 h-4 mr-2" />
                Copy
              </Button>
              <Button variant="secondary" onClick={handleShareAlert} disabled={isSharing || !alertContent} className="w-full">
                <Share2 className="w-4 h-4 mr-2" />
                Share
              </Button>
              <Button variant="secondary" onClick={handleDownloadAlert} className="w-full">
                <Download className="w-4 h-4 mr-2" />
                Save
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Generate Alert Modal */}
      {showGenerateModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
          <div className="bg-surface border border-border p-8 rounded-2xl w-full max-w-md shadow-card">
            <div className="flex items-center justify-between mb-6">
              <h3 className="text-xl font-display font-bold text-white flex items-center">
                <ShieldAlert className="w-6 h-6 text-danger mr-2" />
                Generate Alert
              </h3>
              <button onClick={handleCloseModal} className="text-gray-400 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            <p className="text-gray-400 mb-6 text-sm">
              Review the alert content below before sharing it with your community to help protect others from this scam.
            </p>

            <div className="space-y-6 mb-8">
              <div className="flex items-start space-x-4">
                <Shield className="w-6 h-6 text-danger mt-1 flex-shrink-0" />
                <div>
                  <p className="font-semibold text-white">Verified Threat</p>
                  <p className="text-gray-400 text-sm">Based on AI analysis and community intelligence</p>
                </div>
              </div>

              <div className="flex items-start space-x-4">
                <Users className="w-6 h-6 text-primary mt-1 flex-shrink-0" />
                <div>
                  <p className="font-semibold text-white">Community Protection</p>
                  <p className="text-gray-400 text-sm">Your alert helps protect others in the network</p>
                </div>
              </div>
            </div>

            <Button onClick={handleGenerateAlert} className="w-full h-12 bg-success hover:bg-success/80 text-white border-0">
              <CheckCircle2 className="w-5 h-5 mr-2" />
              Generate Alert
            </Button>
          </div>
        </div>
      )}

      {/* Preview Alert Modal */}
      {showPreviewModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
          <div className="bg-surface border border-border p-8 rounded-2xl w-full max-w-2xl max-h-[90vh] flex flex-col shadow-card">
            <div className="flex items-center justify-between mb-6 flex-shrink-0">
              <h3 className="text-xl font-display font-bold text-white flex items-center">
                <Eye className="w-6 h-6 text-primary mr-2" />
                Alert Preview
              </h3>
              <button onClick={handleCloseModal} className="text-gray-400 hover:text-white transition-colors">
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="bg-background/50 border border-border/50 rounded-xl p-4 mb-6 overflow-y-auto flex-1 font-mono text-sm text-gray-300">
              <pre className="whitespace-pre-wrap">{alertContent}</pre>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 flex-shrink-0">
              <Button onClick={handleCopyAlert} disabled={isSharing} className="w-full">
                <Copy className="w-4 h-4 mr-2" />
                {isSharing ? 'Sharing...' : 'Copy Alert'}
              </Button>
              <Button onClick={handleShareAlert} disabled={isSharing} className="w-full">
                <Share2 className="w-4 h-4 mr-2" />
                {isSharing ? 'Sharing...' : 'Share Alert'}
              </Button>
              <Button onClick={handleDownloadAlert} className="w-full">
                <Download className="w-4 h-4 mr-2" />
                Download Alert
              </Button>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Modal */}
      {showConfirmationModal && (
        <div className="fixed inset-0 bg-background/80 backdrop-blur-md flex items-center justify-center z-50 p-4">
          <div className="bg-surface border border-border p-8 rounded-2xl w-full max-w-md text-center shadow-card">
            <div className="flex justify-center mb-6">
              <div className="w-16 h-16 bg-success/20 rounded-full flex items-center justify-center">
                <CheckCircle2 className="w-8 h-8 text-success" />
              </div>
            </div>
            
            <h3 className="text-2xl font-display font-bold text-white mb-2">
              Shield Activated
            </h3>
            <p className="text-gray-400 mb-8 text-sm">
              Your alert has strengthened the Community Threat Intelligence Network.
            </p>

            <div className="bg-background/50 border border-border/50 rounded-xl p-4 text-left space-y-4 mb-8">
              <div className="flex items-center justify-between">
                <span className="text-gray-400 text-sm flex items-center"><Shield className="w-4 h-4 mr-2" /> Campaign</span>
                <span className="text-white font-mono text-sm">{result.community_intelligence?.threat_id || 'SMR-' + Date.now().toString(36).toUpperCase()}</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-400 text-sm flex items-center"><Users className="w-4 h-4 mr-2" /> Reports</span>
                <span className="text-white font-mono text-sm">{result.community_intelligence?.report_count || 0}+</span>
              </div>
              <div className="flex items-center justify-between">
                <span className="text-gray-400 text-sm flex items-center"><Activity className="w-4 h-4 mr-2" /> Status</span>
                <span className="text-success font-mono text-sm font-bold animate-pulse">ACTIVE</span>
              </div>
            </div>

            <Button onClick={handleCloseModal} className="w-full bg-success hover:bg-success/80 text-white border-0 h-12">
              Dismiss
            </Button>
          </div>
        </div>
      )}
    </>
  );
};

export default ProtectOthersSection;
