import React, { useState, useContext } from 'react';
import { useAnalysis } from '../../context/AnalysisContext';

const ProtectOthersSection = () => {
  const { analysisResult: result } = useAnalysis();
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [showPreviewModal, setShowPreviewModal] = useState(false);
  const [showConfirmationModal, setShowConfirmationModal] = useState(false);
  const [alertContent, setAlertContent] = useState('');
  const [isSharing, setIsSharing] = useState(false);

  if (!result) return null;

  // Generate alert content based on analysis result and community intelligence
  const generateAlertContent = () => {
    const threatId = result.community_intelligence?.threat_id || `SMR-${Date.now().toString(36).toUpperCase()}`;
    const threatFamily = result.community_intelligence?.threat_family || result.category || 'Unknown';
    const threatLevel = getThreatLevel(result.verdict, result.confidence);
    const reportCount = result.community_intelligence?.report_count || 0;
    const timestamp = new Date().toLocaleString();
    const explanation = result.explanation || 'No explanation available.';
    const safetyRecommendations = Array.isArray(result.recommended_actions) && result.recommended_actions.length > 0
      ? result.recommended_actions.join('\n')
      : 'No specific safety recommendations available.';

    return `
🚨 COMMUNITY ALERT: ${threatFamily} Scam Detected 🚨

Threat ID: ${threatId}
Threat Family: ${threatFamily}
Threat Level: ${threatLevel}
Community Reports: ${reportCount} reports in our network
Detection Time: ${timestamp}

📝 AI Analysis:
${explanation}

🛡️ Safety Recommendations:
${safetyRecommendations}

This alert was generated by ScamMirror AI to help protect our community threat intelligence network.
Stay vigilant and report suspicious activity.

#ScamAlert #CommunityShield
    `.trim();
  };

  const getThreatLevel = (verdict, confidence) => {
    const lower = verdict.toLowerCase();
    if (lower.includes('scam') || confidence >= 0.7) return 'HIGH';
    if (lower.includes('safe') || confidence <= 0.3) return 'LOW';
    return 'MEDIUM';
  };

  const handleGenerateAlert = () => {
    setAlertContent(generateAlertContent());
    setShowGenerateModal(false);
    setShowPreviewModal(true);
  };

  const handleCopyAlert = async () => {
    try {
      await navigator.clipboard.writeText(alertContent);
      alert('Alert copied to clipboard!');
    } catch (err) {
      console.error('Failed to copy: ', err);
      alert('Failed to copy alert to clipboard');
    }
  };

  const handleShareAlert = async () => {
    setIsSharing(true);
    try {
      if (navigator.share) {
        await navigator.share({
          title: `Scam Alert: ${result.community_intelligence?.threat_family || result.category || 'Unknown'} Scam Detected`,
          text: alertContent,
        });
        // Success - show confirmation
        setIsSharing(false);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
      } else {
        // Fallback to copy
        await navigator.clipboard.writeText(alertContent);
        setIsSharing(false);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
        alert('Alert copied to clipboard. Share it manually to protect others.');
      }
    } catch (err) {
      console.error('Share failed: ', err);
      setIsSharing(false);
      // Fallback to copy on error
      try {
        await navigator.clipboard.writeText(alertContent);
        setShowPreviewModal(false);
        setShowConfirmationModal(true);
        alert('Alert copied to clipboard. Share it manually to protect others.');
      } catch (copyErr) {
        alert('Failed to share or copy alert');
      }
    }
  };

  const handleDownloadAlert = () => {
    // Download as .txt file
    const blob = new Blob([alertContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `scam-alert-${result.community_intelligence?.threat_id || 'unknown'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCloseModal = () => {
    setShowGenerateModal(false);
    setShowPreviewModal(false);
    setShowConfirmationModal(false);
    setIsSharing(false);
  };

  return (
    <>
      <div className='bg-[#111113/50] backdrop-blur-sm rounded-2xl border border-[#111113/30] p-6'>
        <h3 className='text-xl font-bold text-white flex items-center mb-4'>
          <span className='mr-2'>🛡️</span>
          Community Shield
        </h3>

        <p className='text-gray-300 mb-4'>
          Help protect our community by sharing verified scam alerts. Generate a community alert to warn others about this threat.
        </p>

        <div className='space-y-3'>
          <button
            onClick={() => setShowGenerateModal(true)}
            className='w-full bg-gradient-to-r from-[#FF4D6D] to-[#FF9E8D] hover:from-[#FF6B8B] hover:to-[#FFB7A0] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1'
          >
            <span className='mr-2'>🚨</span>
            Generate Community Alert
          </button>

          <div className='flex space-x-2'>
            <button
              onClick={handleCopyAlert}
              className={`flex-1 bg-gradient-to-r from.[10b981] to.[059669] hover:from-[34d399] hover:to-[10b981] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 ${isSharing ? 'opacity-50 cursor-wait' : ''}`}
              disabled={isSharing}
            >
              <span className='mr-2'>📋</span>
              {isSharing ? 'Sharing...' : 'Copy Alert'}
            </button>

            <button
              onClick={handleShareAlert}
              className={`flex-1 bg-gradient-to-r from.[6366F1] to.[8B5CF6] hover:from-[7C3AED] hover:to-[A78BFA] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 ${isSharing ? 'opacity-50 cursor-wait' : ''}`}
              disabled={isSharing || !alertContent}
            >
              <span className='mr-2'>📤</span>
              {isSharing ? 'Sharing...' : 'Share Alert'}
            </button>

            <button
              onClick={handleDownloadAlert}
              className={`flex-1 bg-gradient-to-r from.[8B5CF6] to.[6366F1] hover:from-[A78BFA] hover:to-[7C3AED] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1`}
            >
              <span className='mr-2'>💾</span>
              Download Alert
            </button>
          </div>
        </div>
      </div>

      {/* Generate Alert Modal */}
      {showGenerateModal && (
        <div className='fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50'>
          <div className='bg-[#111113/80] backdrop-blur-sm rounded-3xl border border-[#111113/40] p-8 w-full max-w-md'>
            <div className='flex items-center justify-between mb-6'>
              <h3 className='text-xl font-bold text-white flex items-center'>
                <span className='mr-2'>🚨</span>
                Generate Community Alert
              </h3>
              <button onClick={handleCloseModal} className='text-gray-400 hover:text-white hover:bg-[#111113/30] rounded-full p-2'>
                ✕
              </button>
            </div>

            <p className='text-gray-300 mb-6'>
              Review the alert content below before sharing it with your community to help protect others from this scam.
            </p>

            <div className='space-y-4'>
              <div className='flex items-center space-x-3'>
                <span className='flex-shrink-0 text-2xl'>🚨</span>
                <div>
                  <p className='font-semibold text-white'>Verified Threat</p>
                  <p className='text-gray-400 text-sm'>
                    Based on AI analysis and community intelligence
                  </p>
                </div>
              </div>

              <div className='flex items-center space-x-3'>
                <span className='flex-shrink-0 text-2xl'>👥</span>
                <div>
                  <p className='font-semibold text-white'>Community Protection</p>
                  <p className='text-gray-400 text-sm'>
                    Your alert helps protect others in the network
                  </p>
                </div>
              </div>

              <div className='flex items-center space-x-3'>
                <span className='flex-shrink-0 text-2xl'>⚡</span>
                <div>
                  <p className='font-semibold text-white'>Instant Sharing</p>
                  <p className='text-gray-400 text-sm'>
                    Share via any app or copy to clipboard
                  </p>
                </div>
              </div>
            </div>

            <div className='mt-8 pt-4 border-t border-[#111113/20]'>
              <button
                onClick={handleGenerateAlert}
                className='w-full bg-gradient-to-r from.[22C55E] to.[16a34a] hover:from-[34d399] hover:to-[22c55e] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1'
              >
                <span className='mr-2'>✅</span>
                Generate Alert
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Preview Alert Modal */}
      {showPreviewModal && (
        <div className='fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50'>
          <div className='bg-[#111113/80] backdrop-blur-sm rounded-3xl border border-[#111113/40] p-8 w-full max-w-2xl max-h-[80vh] overflow-y-auto'>
            <div className='flex items-center justify-between mb-6'>
              <h3 className='text-xl font-bold text-white flex items-center'>
                <span className='mr-2'>👁️</span>
                Alert Preview
              </h3>
              <button onClick={handleCloseModal} className='text-gray-400 hover:text-white hover:bg-[#111113/30] rounded-full p-2'>
                ✕
              </button>
            </div>

            <div className='bg-[#111113/40] rounded-xl p-4 mb-6'>
              <pre className='text-sm text-gray-200 whitespace-pre-wrap'>{alertContent}</pre>
            </div>

            <div className='space-y-3'>
              <button
                onClick={handleCopyAlert}
                className={`w-full bg-gradient-to-r from.[10b981] to.[059669] hover:from-[34d399] hover:to-[10b981] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 ${isSharing ? 'opacity-50 cursor-wait' : ''}`}
                disabled={isSharing}
              >
                <span className='mr-2'>📋</span>
                {isSharing ? 'Sharing...' : 'Copy Alert'}
              </button>

              <button
                onClick={handleShareAlert}
                className={`w-full bg-gradient-to-r from.[6366F1] to.[8B5CF6] hover:from-[7C3AED] hover:to-[A78BFA] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 ${isSharing ? 'opacity-50 cursor-wait' : ''}`}
                disabled={isSharing}
              >
                <span className='mr-2'>📤</span>
                {isSharing ? 'Sharing...' : 'Share Alert'}
              </button>

              <button
                onClick={handleDownloadAlert}
                className={`w-full bg-gradient-to-r from.[8B5CF6] to.[6366F1] hover:from-[A78BFA] hover:to-[7C3AED] text-white font-bold py-3 px-4 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1`}
              >
                <span className='mr-2'>💾</span>
                Download Alert
              </button>
            </div>

            <div className='mt-6 pt-4 border-t border-[#111113/20] text-sm text-gray-400'>
              <p>Share this alert via social media, messaging apps, or email to warn others in your network.</p>
            </div>
          </div>
        </div>
      )}

      {/* Confirmation Modal */}
      {showConfirmationModal && (
        <div className='fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50'>
          <div className='bg-[#111113/80] backdrop-blur-sm rounded-3xl border border-[#111113/40] p-8 text-center max-w-md'>
            <div className='space-y-6'>
              <div className='flex items-center justify-center mb-4'>
                <span className='text-4xl text-[#22C55E]'>✅</span>
              </div>
              <h3 className='font-bold text-white mb-3'>
                Community Shield Activated
              </h3>
              <p className='text-gray-300'>
                Your alert has strengthened the Community Threat Intelligence Network.
              </p>
              <div className='space-y-4 text-left'>
                <div className='flex items-center'>
                  <span className='mr-3'>🏷️</span>
                  <div>
                    <p className='font-semibold text-sm'>Campaign:</p>
                    <p className='text-white'>${result.community_intelligence?.threat_id || 'SMR-' + Date.now().toString(36).toUpperCase()}</p>
                  </div>
                </div>
                <div className='flex items-center'>
                  <span className='mr-3'>👥</span>
                  <div>
                    <p className='font-semibold text-sm'>Community Reports:</p>
                    <p className='text-white'>${result.community_intelligence?.report_count || 0}+</p>
                  </div>
                </div>
                <div className='flex items-center'>
                  <span className='mr-3'>📊</span>
                  <div>
                    <p className='font-semibold text-sm'>Status:</p>
                    <p className='text-white'>ACTIVE</p>
                    <p className='text-gray-400 text-sm'>Threat intelligence updated</p>
                  </div>
                </div>
              </div>
              <p className='text-gray-300 mt-4'>
                Thank you for helping protect others.
              </p>
              <button
                onClick={handleCloseModal}
                className='w-full bg-gradient-to-r from.[22C55E] to.[16a34a] hover:from-[34d399] hover:to-[22c55e] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1'
              >
                <span className='mr-2'>✅</span>
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default ProtectOthersSection;
