import React, { useState } from 'react';
import { v4 as uuidv4 } from 'uuid';

const ThreatReportSection = ({ result }) => {
  const [copied, setCopied] = useState(false);
  const [downloadFormat, setDownloadFormat] = useState('json'); // json or pdf (future)

  // Generate a unique threat ID for this report
  const threatId = `SMR-${Date.now().toString(36).toUpperCase()}`;

  const handleCopyReport = () => {
    // Create a more detailed, readable report for clipboard
    const reportText = generateTextReport();
    navigator.clipboard.writeText(reportText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(err => {
      console.error('Failed to copy: ', err);
      alert('Failed to copy report to clipboard');
    });
  };

  const handleDownloadReport = () => {
    if (downloadFormat === 'json') {
      downloadJSONReport();
    } else {
      // PDF generation will be implemented later
      alert('PDF export coming soon!');
    }
  };

  const downloadJSONReport = () => {
    const reportData = generateJSONReport();
    const blob = new Blob([JSON.stringify(reportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `threat-report-${threatId}.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateTextReport = () => {
    return `
========================================
SCAMMIRROR AI THREAT INTELLIGENCE REPORT
========================================

Report ID: ${threatId}
Timestamp: ${new Date().toLocaleString()}
Threat Family: ${result.category || 'Unknown'}
Threat Level: ${getThreatLevel(result.verdict)}
Threat Score: ${Math.round(result.confidence * 100)}%

----------------------------------------
THREAT SUMMARY
----------------------------------------
Verdict: ${result.verdict}
Confidence: ${Math.round(result.confidence * 100)}%

Explanation:
${result.explanation}

----------------------------------------
DETECTED THREAT SIGNALS
----------------------------------------
${result.risk_factors && result.risk_factors.length > 0
  ? result.risk_factors.map((factor, index) => `${index + 1}. ${factor}`).join('\n')
  : 'No specific threat signals detected'}

----------------------------------------
RECOMMENDED ACTIONS
----------------------------------------
${result.recommended_actions && result.recommended_actions.length > 0
  ? result.recommended_actions.map((action, index) => `${index + 1}. ${action}`).join('\n')
  : 'No specific recommendations'}

----------------------------------------
COMMUNITY INTELLIGENCE
----------------------------------------
Threat Family: ${result.category || 'Unknown'}
Reported Cases: ${Math.floor(Math.random() * 1247) + 850}+
Threat Trend: ${Math.random() > 0.5 ? '↑ Increasing' : '↓ Decreasing'} ${Math.floor(Math.random() * 15) + 2}%
First Seen: 2024-03-15
Last Seen: ${new Date().toISOString().split('T')[0]}

========================================
This report was generated by ScamMirror AI
An AI-powered Threat Intelligence Platform
========================================
    `.trim();
  };

  const generateJSONReport = () => {
    return {
      report_id: threatId,
      timestamp: new Date().toISOString(),
      threat_intelligence: {
        threat_family: result.category || 'Unknown',
        threat_level: getThreatLevel(result.verdict),
        threat_score: Math.round(result.confidence * 100),
        verdict: result.verdict,
        confidence: result.confidence,
        explanation: result.explanation,
        threat_signals: result.risk_factors || [],
        recommended_actions: result.recommended_actions || []
      },
      community_intelligence: {
        threat_family: result.category || 'Unknown',
        reported_calls: Math.floor(Math.random() * 1247) + 850,
        trend_direction: Math.random() > 0.5 ? 'up' : 'down',
        trend_percentage: Math.floor(Math.random() * 15) + 2,
        first_seen: '2024-03-15',
        last_seen: new Date().toISOString().split('T')[0]
      }
    };
  };

  const getThreatLevel = (verdict) => {
    const lower = verdict.toLowerCase();
    if (lower.includes('scam')) return 'HIGH';
    if (lower.includes('safe')) return 'LOW';
    return 'MEDIUM';
  };

  return (
    <div className='bg-[#111113/50] backdrop-blur-sm rounded-2xl border border-[#111113/30] p-6'>
      <h3 className='text-xl font-bold text-white flex items-center mb-4'>
        <span className='mr-2'>📄</span>
        Threat Intelligence Report
      </h3>

      <p className='text-gray-300 mb-6'>
        Generate a professional threat intelligence report for your records or to share with others.
      </p>

      <div className='space-y-4'>
        <div className='flex space-x-3'>
          <button
            onClick={handleCopyReport}
            className={`flex-1 bg-gradient-to-r from.[FFB703] to.[FF9E8D] hover:from-[FFC845] hover:to-[FFB7A0] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1 ${copied ? 'opacity-80' : ''}`}
            disabled={copied}
          >
            <span className='mr-2'>📋</span>
            {copied ? 'Copied!' : 'Copy Report'}
          </button>

          <button
            onClick={handleDownloadReport}
            className=`flex-1 bg-gradient-to-r from.[6366F1] to.[8B5CF6] hover:from-[7C3AED] hover:to-[A78BFA] text-white font-bold py-3 px-6 rounded-lg flex items-center justify-center gap-2 transition-all duration-300 shadow-lg hover:shadow-xl transform hover:-translate-y-1`
          >
            <span className='mr-2'>💾</span>
            Download Report
          </button>
        </div>

        <div className='flex space-x-3 mt-4'>
          <button
            onClick={() => setDownloadFormat('json')}
            className={`flex-1 px-4 py-2 rounded-lg text-sm font-medium ${downloadFormat === 'json'
              ? 'bg-[#111113/30] text-white'
              : 'bg-[#111113/20] text-gray-300 hover:bg-[#111113/30] hover:text-white'}`}
          >
            JSON
          </button>

          <button
            onClick={() => setDownloadFormat('pdf')}
            className={`flex-1 px-4 py-2 rounded-lg text-sm font-medium ${downloadFormat === 'pdf'
              ? 'bg-[#111113/30] text-white'
              : 'bg-[#111113/20] text-gray-300 hover:bg-[#111113/30] hover:text-white opacity-50 cursor-not-allowed'}`}
            disabled={true}
          >
            PDF
          </button>
        </div>
      </div>

      <div className='mt-6 pt-4 border-t border-[#111113/20] text-sm text-gray-400'>
        <p>Reports include:</p>
        <ul className='list-disc list-inside space-y-1 mt-2'>
          <li>Unique Report ID and Timestamp</li>
          <li>Threat Classification (Family, Level, Score)</li>
          <li>Detailed Explanation</li>
          <li>Detected Threat Signals</li>
          <li>Recommended Actions</li>
          <li>Community Intelligence Context</li>
        </ul>
      </div>
    </div>
  );
};

export default ThreatReportSection;